[package]
name = "di-dev-enclave"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "di-dev-enclave"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
di-dev-enclave-types.workspace = true
pontifex = { workspace = true, features = ["server"] }
tokio = { workspace = true, features = ["macros"] }
tracing.workspace = true
tracing-subscriber.workspace = true
